[build]
  base = "frontend"           # importante: build desde el subdirectorio frontend
  command = "npm install && npm run build"
  publish = ".next"  # publica el build de Next.js
  functions = ".netlify/functions" # serverless functions generadas por el plugin


[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"